export type View='overview'|'orders'|'catalogue'|'menus'|'storefronts'|'inventory'|'finance'|'integrations'|'branches'|'settings';
export const modules:{id:View;label:string}[]=[{id:'overview',label:'Overview'},{id:'orders',label:'Orders'},{id:'catalogue',label:'Catalogue'},{id:'menus',label:'Menus'},{id:'storefronts',label:'Storefronts'},{id:'inventory',label:'Inventory'},{id:'finance',label:'Finance'},{id:'integrations',label:'Integrations'},{id:'branches',label:'Branches'},{id:'settings',label:'Settings'}];
export const branches=['HBZ Stadium','HCT Academic City','Al Ain Zoo'];
export type Product={id:string;name:string;category:string;price:number;sku:string;status:string};
export type Order={id:string;customer:string;branch:string;channel:string;status:string;time:string;total:number;items:{name:string;qty:number;price:number}[]};
export const seed={version:1,role:'Administrator',orders:[
{id:'Q-1086',customer:'Amal Hassan',branch:branches[0],channel:'Storefront',status:'New',time:'15:18',total:72,items:[{name:'Spanish Latte',qty:2,price:24},{name:'Almond Croissant',qty:1,price:24}]},
{id:'Q-1085',customer:'Omar Khalid',branch:branches[1],channel:'POS',status:'Preparing',time:'15:14',total:46,items:[{name:'Flat White',qty:1,price:22},{name:'Almond Croissant',qty:1,price:24}]},
{id:'Q-1084',customer:'Sarah Ahmed',branch:branches[0],channel:'Storefront',status:'Ready',time:'15:10',total:56,items:[{name:'Matcha Latte',qty:2,price:28}]},
{id:'Q-1083',customer:'James Wilson',branch:branches[2],channel:'Storefront',status:'New',time:'15:06',total:48,items:[{name:'Spanish Latte',qty:2,price:24}]},
{id:'Q-1082',customer:'Layla Saeed',branch:branches[1],channel:'POS',status:'Completed',time:'15:02',total:40,items:[{name:'Americano',qty:2,price:20}]},
{id:'Q-1081',customer:'Daniel Costa',branch:branches[0],channel:'Storefront',status:'Preparing',time:'14:58',total:74,items:[{name:'Flat White',qty:1,price:22},{name:'Avocado Toast',qty:1,price:52}]},
{id:'Q-1080',customer:'Noor Ali',branch:branches[2],channel:'Manual',status:'Completed',time:'14:53',total:28,items:[{name:'Matcha Latte',qty:1,price:28}]},
{id:'Q-1079',customer:'Rashid Salem',branch:branches[0],channel:'POS',status:'Completed',time:'14:46',total:44,items:[{name:'Flat White',qty:2,price:22}]}] as Order[],
products:[{id:'p1',name:'Spanish Latte',category:'Coffee',price:24,sku:'Q-CF-001',status:'Available'},{id:'p2',name:'Flat White',category:'Coffee',price:22,sku:'Q-CF-002',status:'Available'},{id:'p3',name:'Americano',category:'Coffee',price:20,sku:'Q-CF-003',status:'Available'},{id:'p4',name:'Matcha Latte',category:'Tea',price:28,sku:'Q-TE-001',status:'Available'},{id:'p5',name:'Almond Croissant',category:'Food',price:24,sku:'Q-FD-001',status:'Available'},{id:'p6',name:'Avocado Toast',category:'Food',price:52,sku:'Q-FD-002',status:'Draft'}] as Product[],
menus:[{id:'m1',name:'The everyday collection',branch:branches[0],status:'Published',version:12,arabic:true,products:['p1','p2','p3','p4','p5']},{id:'m2',name:'Campus favourites',branch:branches[1],status:'Published',version:8,arabic:true,products:['p1','p2','p3','p5']},{id:'m3',name:'A little afternoon escape',branch:branches[2],status:'Draft',version:3,arabic:false,products:['p1','p4','p5']}],
storefront:{name:'Quotes Coffee',domain:'quotes.dev.qosapp.com',version:8,languages:'English + Arabic'},
inventory:[{id:'i1',name:'House blend coffee beans',supplier:'Roastery Supply Co.',branch:branches[0],stock:8,min:15,unit:'kg'},{id:'i2',name:'Oat milk',supplier:'Daily Fresh',branch:branches[1],stock:24,min:12,unit:'L'},{id:'i3',name:'Matcha powder',supplier:'Tea Collective',branch:branches[2],stock:2,min:4,unit:'kg'},{id:'i4',name:'Whole milk',supplier:'Daily Fresh',branch:branches[0],stock:48,min:20,unit:'L'},{id:'i5',name:'Takeaway cups',supplier:'Roastery Supply Co.',branch:branches[1],stock:640,min:250,unit:'pcs'}],
locations:[{id:'b1',name:branches[0],city:'Abu Dhabi',address:'Stadium concourse, main entrance',hours:'07:00 – 23:00',open:true},{id:'b2',name:branches[1],city:'Dubai',address:'Academic City, campus building',hours:'07:00 – 21:00',open:true},{id:'b3',name:branches[2],city:'Al Ain',address:'Visitor centre, main plaza',hours:'09:00 – 20:00',open:true}],
integrations:[{id:'stripe',name:'Stripe',description:'Payments and checkout sessions.',connected:true,synced:'2 minutes ago'},{id:'pos',name:'POS connector',description:'Orders, products and availability.',connected:true,synced:'5 minutes ago'},{id:'finedine',name:'FineDine',description:'Menu import and catalogue mapping.',connected:false,synced:'—'}],
activity:[{id:'a1',text:'New order Q-1086 received at HBZ Stadium',time:'4 minutes ago'},{id:'a2',text:'Campus favourites menu published · v8',time:'26 minutes ago'},{id:'a3',text:'Quotes storefront release v8 is active',time:'1 hour ago'},{id:'a4',text:'POS catalogue sync completed',time:'2 hours ago'}]};
export type Demo=typeof seed;
