import { and, desc, eq, gte, inArray, isNull, sql } from "drizzle-orm";
import sharp from "sharp";

import type { DbClient } from "@/db/client";
import {
  aiJobs,
  aiSpendReservations,
  catalogueMediaAssets,
  catalogueMediaUploadGrants,
  catalogueProducts,
  catalogueProductTranslations,
} from "@/db/schema";
import { cancelUnclaimedAiJobInTx, enqueueAiJobInTx } from "@/lib/ai/jobs/ai-job-queue";
import type { ProviderOutcome } from "@/lib/ai/provider-outcome";
import {
  AiSpendAdmissionError,
  releaseUnstartedAiSpend,
  reserveAiSpend,
  type AiSpendAdmissionErrorCode,
} from "@/lib/ai/spend/spend-admission";
import { aiSpendReadiness, readAiSpendPolicy, type AiSpendPolicy } from "@/lib/ai/spend/spend-policy";
import {
  auditActorClassFromStaffRole,
  recordTenantAuditEventInTx,
  type AuditActorClass,
} from "@/lib/audit/tenant-audit";
import { assertMenuLocationAccess, loadDraftMenuEditorView, MenuError } from "@/lib/catalogue/menus";
import {
  aiPhotoUnavailableReason,
  readAiPhotoConfig,
  type AiPhotoConfig,
  type AiPhotoExecutionMode,
  type AiPhotoUnavailableReason,
} from "@/lib/media/ai-photos/config";
import {
  AI_PHOTO_PROMPT_VERSION,
  aiPhotoContextSha256,
  buildAiPhotoPrompt,
  type AiPhotoProductContext,
} from "@/lib/media/ai-photos/prompt";
import {
  AiPhotoProviderError,
  type AiPhotoProviderDiagnostics,
  getAiPhotoProvider,
  hasAiPhotoProviderOverride,
  type AiPhotoProvider,
  type AiPhotoUsage,
} from "@/lib/media/ai-photos/provider";
import { readMediaConfig } from "@/lib/media/config";
import {
  createProductImageUploadGrantInTx,
  getApprovedThumbnailPublicIdsForProducts,
  ingestProductImageUpload,
  processProductImageInTx,
} from "@/lib/media/product-images";
import { getMediaStorage } from "@/lib/media/storage";
import type { ActiveStaffMembership } from "@/lib/staff/auth";
import { StaffAuthorizationError } from "@/lib/staff/auth";
import { withTenantContext, type DbTransaction } from "@/lib/tenant/context";

export const AI_PHOTO_METADATA_SCHEMA = "qos.ai_photo_generation.v1";
const QUOTA_WINDOW_MS = 24 * 60 * 60 * 1000;
const MAX_OUTPUT_DIMENSION = 1536;

export class AiPhotoError extends Error {
  readonly code: string;
  readonly statusCode: number;

  constructor(code: string, message: string, statusCode: number) {
    super(message);
    this.name = "AiPhotoError";
    this.code = code;
    this.statusCode = statusCode;
  }
}

export type AiPhotoCaller = {
  tenantId: string;
  subject: string;
  membership: ActiveStaffMembership;
};

type ServiceOptions = {
  config?: AiPhotoConfig;
  provider?: AiPhotoProvider;
  now?: () => Date;
  spendPolicy?: AiSpendPolicy;
};

export const AI_PHOTO_JOB_KIND = "ai_photo.generate" as const;
export const AI_PHOTO_SPEND_PATH = "ai_photo.async" as const;
/** Spend is admitted against the paid provider; the local mock is never used with queued mode in production. */
export const AI_PHOTO_SPEND_PROVIDER = "openai" as const;
export const AI_PHOTO_SPEND_SUBJECT = "catalogue_media_asset";
export const AI_PHOTO_MAX_BATCH = 50;

export type AiPhotoActor = { subject: string; actorClass: AuditActorClass };

/** Review state as staff see it; derived from the media asset status. */
export type AiPhotoCandidateStatus = "generating" | "pending_review" | "accepted" | "rejected" | "failed";

export type AiPhotoCandidateView = {
  assetPublicId: string;
  productPublicId: string;
  status: AiPhotoCandidateStatus;
  failureCode: string | null;
  createdAt: string;
  previewPath: string | null;
};

export type AiPhotoAvailabilityView = {
  available: boolean;
  unavailableReason: AiPhotoUnavailableReason | null;
  /** Generating spends provider budget, so only administrators may start or accept it. */
  canGenerate: boolean;
  dailyLimit: number;
  usedToday: number;
  remainingToday: number;
  /** `queued_worker`: requests are admitted in batches and generated by the AI worker; poll for progress. */
  executionMode: AiPhotoExecutionMode;
};

export type MenuAiPhotosView = {
  availability: AiPhotoAvailabilityView;
  candidates: AiPhotoCandidateView[];
  /** Products whose current approved photo is an accepted AI image (label it as such). */
  aiPhotoProductPublicIds: string[];
};

export type GenerationMetadata = {
  schema: typeof AI_PHOTO_METADATA_SCHEMA;
  provider: string;
  model: string;
  quality: string;
  promptVersion: string;
  prompt: string;
  contextSha256: string;
  menuPublicId: string;
  requestedBySubject: string;
  requestedAt: string;
  /** Absent on candidates created before queued execution existed: they were all `sync`. */
  executionMode?: AiPhotoExecutionMode;
  spendReservationPublicId?: string;
  completedAt?: string;
  usage?: AiPhotoUsage | null;
  failureCode?: string;
  /** What the provider outcome proved when generation failed; decides whether the attempt counts. */
  providerOutcome?: ProviderOutcome;
  review?: {
    decision: "accepted" | "rejected";
    decidedBySubject: string;
    decidedAt: string;
    accuracyConfirmed?: boolean;
    replacedAssetPublicId?: string | null;
  };
};

function toStatus(status: (typeof catalogueMediaAssets.$inferSelect)["status"]): AiPhotoCandidateStatus {
  switch (status) {
    case "pending_upload":
    case "processing":
      return "generating";
    case "uploaded":
      return "pending_review";
    case "approved":
      return "accepted";
    case "rejected":
      return "rejected";
    case "failed":
      return "failed";
  }
}

export function metadataOf(asset: { generationMetadata: Record<string, unknown> | null }) {
  return (asset.generationMetadata ?? {}) as Partial<GenerationMetadata>;
}

function candidatePreviewPath(tenantId: string, menuPublicId: string, assetPublicId: string) {
  return `/api/tenants/${tenantId}/catalogue/menus/${menuPublicId}/ai-photos/${assetPublicId}/preview`;
}

function toCandidateView(
  tenantId: string,
  menuPublicId: string,
  productPublicId: string,
  asset: typeof catalogueMediaAssets.$inferSelect,
): AiPhotoCandidateView {
  const status = toStatus(asset.status);
  return {
    assetPublicId: asset.publicId,
    productPublicId,
    status,
    failureCode: status === "failed" ? (metadataOf(asset).failureCode ?? "generation_failed") : null,
    createdAt: asset.createdAt.toISOString(),
    previewPath:
      status === "pending_review" ? candidatePreviewPath(tenantId, menuPublicId, asset.publicId) : null,
  };
}

function requireAdministrator(caller: AiPhotoCaller) {
  if (caller.membership.role !== "administrator") {
    throw new StaffAuthorizationError("Only administrators can generate or accept AI photos.");
  }
}

function resolveAvailability(config: AiPhotoConfig, options: ServiceOptions) {
  return aiPhotoUnavailableReason(config, {
    providerOverride: Boolean(options.provider) || hasAiPhotoProviderOverride(),
    spendAdmissible:
      config.executionMode === "queued_worker" &&
      aiSpendReadiness(options.spendPolicy ?? readAiSpendPolicy(), AI_PHOTO_SPEND_PATH, AI_PHOTO_SPEND_PROVIDER)
        .admissible,
  });
}

type MenuProduct = {
  id: string;
  publicId: string;
  primaryMediaAssetId: string | null;
  context: AiPhotoProductContext;
};

/** Non-archived placements of the menu, with the approved English text used for prompts. */
async function loadMenuProducts(
  tx: DbTransaction,
  tenantId: string,
  menuPublicId: string,
  productPublicIds?: readonly string[],
): Promise<Map<string, MenuProduct>> {
  const menu = await loadDraftMenuEditorView(tx, tenantId, menuPublicId);
  if (!menu) {
    throw new MenuError("Menu not found.", 404);
  }

  const sectionNameByProduct = new Map<string, string>();
  for (const section of menu.sections) {
    if (section.archived) {
      continue;
    }
    for (const placement of section.products) {
      if (placement.archived || sectionNameByProduct.has(placement.productPublicId)) {
        continue;
      }
      sectionNameByProduct.set(
        placement.productPublicId,
        section.translations.en.displayName || section.internalName,
      );
    }
  }

  const wanted = [...sectionNameByProduct.keys()].filter(
    (id) => !productPublicIds || productPublicIds.includes(id),
  );
  const result = new Map<string, MenuProduct>();
  if (wanted.length === 0) {
    return result;
  }

  const rows = await tx
    .select({
      id: catalogueProducts.id,
      publicId: catalogueProducts.publicId,
      internalName: catalogueProducts.internalName,
      status: catalogueProducts.status,
      primaryMediaAssetId: catalogueProducts.primaryMediaAssetId,
      displayName: catalogueProductTranslations.displayName,
      description: catalogueProductTranslations.description,
    })
    .from(catalogueProducts)
    .leftJoin(
      catalogueProductTranslations,
      and(
        eq(catalogueProductTranslations.tenantId, catalogueProducts.tenantId),
        eq(catalogueProductTranslations.productId, catalogueProducts.id),
        eq(catalogueProductTranslations.locale, "en"),
      ),
    )
    .where(
      and(eq(catalogueProducts.tenantId, tenantId), inArray(catalogueProducts.publicId, wanted)),
    );

  for (const row of rows) {
    if (row.status === "archived") {
      continue;
    }
    result.set(row.publicId, {
      id: row.id,
      publicId: row.publicId,
      primaryMediaAssetId: row.primaryMediaAssetId,
      context: {
        displayName: row.displayName?.trim() || row.internalName,
        description: row.description,
        sectionName: sectionNameByProduct.get(row.publicId) ?? null,
      },
    });
  }
  return result;
}

async function requireMenuProduct(
  tx: DbTransaction,
  tenantId: string,
  menuPublicId: string,
  productPublicId: string,
) {
  const product = (await loadMenuProducts(tx, tenantId, menuPublicId, [productPublicId])).get(
    productPublicId,
  );
  if (!product) {
    throw new AiPhotoError("product_not_in_menu", "This item is not on the menu.", 404);
  }
  return product;
}

/**
 * Failures where the provider refused the request before generating anything
 * (bad credentials, rate limit, unreachable, not configured), or where QOS
 * never sent it (the requester lost access, the item went away, no worker
 * started it in time), are not billed, so they do not spend the allowance.
 * Timeouts, unusable output and unknown errors may have been billed and still
 * count, and so does any failure whose recorded provider outcome says the
 * provider may have done the work.
 */
export const UNBILLED_FAILURE_CODES = [
  "provider_auth",
  "provider_rate_limited",
  "provider_unreachable",
  "provider_unavailable",
  "ai_photos_unavailable",
  "tenant_inactive",
  "requester_access_revoked",
  "product_unavailable",
  "not_started_in_time",
] as const;

const UNBILLED_OUTCOMES = ["not_dispatched", "rejected"] as const satisfies readonly ProviderOutcome[];

async function countAttemptsInWindow(tx: DbTransaction, tenantId: string, since: Date) {
  const metadata = catalogueMediaAssets.generationMetadata;
  const [row] = await tx
    .select({ count: sql<number>`count(*)::int` })
    .from(catalogueMediaAssets)
    .where(
      and(
        eq(catalogueMediaAssets.tenantId, tenantId),
        eq(catalogueMediaAssets.sourceProvenance, "ai_generated"),
        gte(catalogueMediaAssets.createdAt, since),
        sql`not (${catalogueMediaAssets.status} = 'failed'
          and coalesce(${metadata} ->> 'failureCode', '') in (${sql.join(
            UNBILLED_FAILURE_CODES.map((code) => sql`${code}`),
            sql`, `,
          )})
          and coalesce(${metadata} ->> 'providerOutcome', 'not_dispatched') in (${sql.join(
            UNBILLED_OUTCOMES.map((outcome) => sql`${outcome}`),
            sql`, `,
          )}))`,
      ),
    );
  return Number(row?.count ?? 0);
}

async function lockTenantAiPhotos(tx: DbTransaction, tenantId: string) {
  await tx.execute(sql`select pg_advisory_xact_lock(hashtext(${`qos.ai_photos:${tenantId}`}))`);
}

function availabilityView(
  config: AiPhotoConfig,
  reason: AiPhotoUnavailableReason | null,
  caller: AiPhotoCaller,
  usedToday: number,
): AiPhotoAvailabilityView {
  return {
    available: reason === null,
    unavailableReason: reason,
    canGenerate: reason === null && caller.membership.role === "administrator",
    dailyLimit: config.dailyLimitPerTenant,
    usedToday,
    remainingToday: Math.max(0, config.dailyLimitPerTenant - usedToday),
    executionMode: config.executionMode,
  };
}

export async function getMenuAiPhotos(
  db: DbClient,
  caller: AiPhotoCaller,
  menuPublicId: string,
  options: ServiceOptions = {},
): Promise<MenuAiPhotosView> {
  const config = options.config ?? readAiPhotoConfig();
  const now = options.now?.() ?? new Date();
  const reason = resolveAvailability(config, options);

  return withTenantContext(db, caller.tenantId, async (tx) => {
    await assertMenuLocationAccess(tx, caller.tenantId, caller.membership, menuPublicId);
    const products = await loadMenuProducts(tx, caller.tenantId, menuPublicId);
    const productList = [...products.values()];
    const publicIdById = new Map(productList.map((product) => [product.id, product.publicId]));
    const loadAssets = () =>
      productList.length === 0
        ? Promise.resolve([] as (typeof catalogueMediaAssets.$inferSelect)[])
        : tx
            .select()
            .from(catalogueMediaAssets)
            .where(
              and(
                eq(catalogueMediaAssets.tenantId, caller.tenantId),
                eq(catalogueMediaAssets.sourceProvenance, "ai_generated"),
                inArray(
                  catalogueMediaAssets.productId,
                  productList.map((product) => product.id),
                ),
              ),
            )
            .orderBy(desc(catalogueMediaAssets.createdAt));

    let assets = await loadAssets();
    const stale = assets.filter((asset) => isStaleQueuedRequest(asset, config, now));
    if (stale.length > 0) {
      await lockTenantAiPhotos(tx, caller.tenantId);
      let cancelled = 0;
      for (const asset of stale) {
        if (await cancelStaleQueuedRequestInTx(tx, caller.tenantId, asset, actorOf(caller))) {
          cancelled += 1;
        }
      }
      if (cancelled > 0) {
        assets = await loadAssets();
      }
    }
    const usedToday = await countAttemptsInWindow(
      tx,
      caller.tenantId,
      new Date(now.getTime() - QUOTA_WINDOW_MS),
    );

    const latestByProduct = new Map<string, (typeof assets)[number]>();
    for (const asset of assets) {
      if (!latestByProduct.has(asset.productId)) {
        latestByProduct.set(asset.productId, asset);
      }
    }

    const candidates: AiPhotoCandidateView[] = [];
    for (const asset of latestByProduct.values()) {
      const status = toStatus(asset.status);
      const isRecentFailure =
        status === "failed" && asset.createdAt.getTime() >= now.getTime() - QUOTA_WINDOW_MS;
      if (status === "generating" || status === "pending_review" || isRecentFailure) {
        candidates.push(
          toCandidateView(caller.tenantId, menuPublicId, publicIdById.get(asset.productId)!, asset),
        );
      }
    }

    const approvedAiAssetIds = new Set(
      assets.filter((asset) => asset.status === "approved").map((asset) => asset.id),
    );
    const thumbnails = await getApprovedThumbnailPublicIdsForProducts(tx, caller.tenantId, productList);
    const aiPhotoProductPublicIds = productList
      .filter(
        (product) =>
          product.primaryMediaAssetId !== null &&
          approvedAiAssetIds.has(product.primaryMediaAssetId) &&
          thumbnails.has(product.id),
      )
      .map((product) => product.publicId);

    return {
      availability: availabilityView(config, reason, caller, usedToday),
      candidates,
      aiPhotoProductPublicIds,
    };
  });
}

function actorOf(caller: AiPhotoCaller): AiPhotoActor {
  return { subject: caller.subject, actorClass: auditActorClassFromStaffRole(caller.membership.role) };
}

export type AiPhotoFailure = {
  failureCode: string;
  message: string;
  providerOutcome?: ProviderOutcome;
  providerDiagnostics?: AiPhotoProviderDiagnostics | null;
};

/**
 * Fails an unfinished request inside the caller's tenant transaction: its
 * upload grant is closed and the asset records why. A stored candidate is
 * never downgraded; it is returned unchanged.
 */
export async function failAiPhotoAssetInTx(
  tx: DbTransaction,
  tenantId: string,
  assetId: string,
  failure: AiPhotoFailure,
  actor: AiPhotoActor,
) {
  const [asset] = await tx
    .select()
    .from(catalogueMediaAssets)
    .where(and(eq(catalogueMediaAssets.tenantId, tenantId), eq(catalogueMediaAssets.id, assetId)))
    .limit(1)
    .for("update");
  if (!asset || asset.status !== "pending_upload") {
    return asset ?? null;
  }

  await tx
    .update(catalogueMediaUploadGrants)
    .set({ status: "expired" })
    .where(
      and(
        eq(catalogueMediaUploadGrants.tenantId, tenantId),
        eq(catalogueMediaUploadGrants.assetId, asset.id),
        eq(catalogueMediaUploadGrants.status, "pending"),
      ),
    );

  const { failureCode, providerOutcome, providerDiagnostics } = failure;
  const evidence = {
    ...(providerOutcome ? { providerOutcome } : {}),
    ...(providerDiagnostics ? { providerDiagnostics } : {}),
  };
  const [failed] = await tx
    .update(catalogueMediaAssets)
    .set({
      status: "failed",
      failureReason: failure.message,
      generationMetadata: { ...metadataOf(asset), failureCode, ...evidence },
      updatedAt: new Date(),
    })
    .where(eq(catalogueMediaAssets.id, asset.id))
    .returning();

  await recordTenantAuditEventInTx(tx, {
    tenantId,
    actorSubject: actor.subject,
    actorClass: actor.actorClass,
    action: "catalogue.media.ai_photo_failed",
    entityType: "catalogue_media_asset",
    entityPublicId: asset.publicId,
    changeSummary: { failureCode, ...evidence },
  });
  return failed!;
}

async function markGenerationFailed(
  db: DbClient,
  caller: AiPhotoCaller,
  assetId: string,
  failure: AiPhotoFailure,
) {
  return withTenantContext(db, caller.tenantId, (tx) =>
    failAiPhotoAssetInTx(tx, caller.tenantId, assetId, failure, actorOf(caller)),
  );
}

export const NOT_STARTED_IN_TIME_MESSAGE = "No worker started this photo in time. Nothing was generated or charged.";

function isStaleQueuedRequest(
  asset: typeof catalogueMediaAssets.$inferSelect,
  config: AiPhotoConfig,
  now: Date,
) {
  return (
    asset.status === "pending_upload" &&
    metadataOf(asset).executionMode === "queued_worker" &&
    now.getTime() - asset.createdAt.getTime() >= config.queuedStaleMs
  );
}

/**
 * Closes a queued request that no worker ever claimed: the job is cancelled,
 * the asset fails as never started and its spend is returned. A job a worker
 * has claimed is left to the worker, however old. False when nothing changed.
 */
async function cancelStaleQueuedRequestInTx(
  tx: DbTransaction,
  tenantId: string,
  asset: typeof catalogueMediaAssets.$inferSelect,
  actor: AiPhotoActor,
) {
  const [job] = await tx
    .select({ publicId: aiJobs.publicId })
    .from(aiJobs)
    .where(
      and(
        eq(aiJobs.tenantId, tenantId),
        eq(aiJobs.jobKind, AI_PHOTO_JOB_KIND),
        eq(aiJobs.mediaAssetId, asset.id),
      ),
    )
    .limit(1);
  if (
    !job ||
    !(await cancelUnclaimedAiJobInTx(tx, {
      jobPublicId: job.publicId,
      code: "not_started_in_time",
      message: NOT_STARTED_IN_TIME_MESSAGE,
    }))
  ) {
    return false;
  }

  await failAiPhotoAssetInTx(
    tx,
    tenantId,
    asset.id,
    { failureCode: "not_started_in_time", message: NOT_STARTED_IN_TIME_MESSAGE },
    actor,
  );
  const [reservation] = await tx
    .select({ publicId: aiSpendReservations.publicId })
    .from(aiSpendReservations)
    .where(
      and(
        eq(aiSpendReservations.tenantId, tenantId),
        eq(aiSpendReservations.path, AI_PHOTO_SPEND_PATH),
        eq(aiSpendReservations.subjectType, AI_PHOTO_SPEND_SUBJECT),
        eq(aiSpendReservations.subjectPublicId, asset.publicId),
        eq(aiSpendReservations.state, "reserved"),
        isNull(aiSpendReservations.dispatchedAt),
      ),
    )
    .limit(1);
  if (reservation) {
    await releaseUnstartedAiSpend(tx, { tenantId, reservationPublicId: reservation.publicId });
  }
  return true;
}

/** Re-encodes provider output: rejects anything that is not a decodable image and strips metadata. */
export async function normalizeGeneratedImage(bytes: Buffer) {
  const media = readMediaConfig();
  try {
    const output = await sharp(bytes, {
      failOn: "error",
      limitInputPixels: media.maxPixelDimension * media.maxPixelDimension,
    })
      .rotate()
      .resize({
        width: MAX_OUTPUT_DIMENSION,
        height: MAX_OUTPUT_DIMENSION,
        fit: "inside",
        withoutEnlargement: true,
      })
      .jpeg({ quality: 88, mozjpeg: true })
      .toBuffer();
    if (output.byteLength > media.maxUploadBytes) {
      throw new Error("too large");
    }
    return output;
  } catch {
    throw new AiPhotoProviderError("invalid_output", "The image service returned an unusable image.");
  }
}

export type GenerateAiPhotoResult = {
  candidate: AiPhotoCandidateView;
  /** False when an existing pending candidate was returned instead of spending again. */
  created: boolean;
  /** True when the request was admitted for the AI worker and is still generating. */
  queued: boolean;
};

type MediaAsset = typeof catalogueMediaAssets.$inferSelect;

type ReserveContext = {
  config: AiPhotoConfig;
  now: () => Date;
  /** Required in queued_worker mode. */
  spendPolicy: AiSpendPolicy | null;
};

type Reservation =
  | { kind: "existing"; asset: MediaAsset }
  | { kind: "in_progress" }
  | { kind: "daily_limit_reached" }
  | { kind: "reserved"; asset: MediaAsset; grantToken: string; prompt: string };

const IN_PROGRESS_MESSAGE = "A photo is already being generated for this item.";

function dailyLimitMessage(config: AiPhotoConfig) {
  return `This business has used all ${config.dailyLimitPerTenant} AI photo generations for today.`;
}

/**
 * Reserves one generation for a product inside the caller's tenant
 * transaction, which must already hold the tenant AI photo lock. The spend
 * record (an ai_generated asset) is created before any provider call, so the
 * daily limit cannot be overshot by concurrent requests and failures still
 * count. In queued_worker mode the ai_photo.async spend is admitted and the
 * job enqueued in the same transaction, so admitted work and its job commit
 * together or not at all.
 */
async function reserveAiPhotoInTx(
  tx: DbTransaction,
  caller: AiPhotoCaller,
  menuPublicId: string,
  product: MenuProduct,
  context: ReserveContext,
): Promise<Reservation> {
  const { config, now } = context;
  const mediaConfig = readMediaConfig();

  const [open] = await tx
    .select()
    .from(catalogueMediaAssets)
    .where(
      and(
        eq(catalogueMediaAssets.tenantId, caller.tenantId),
        eq(catalogueMediaAssets.productId, product.id),
        eq(catalogueMediaAssets.sourceProvenance, "ai_generated"),
        inArray(catalogueMediaAssets.status, ["pending_upload", "uploaded"]),
      ),
    )
    .orderBy(desc(catalogueMediaAssets.createdAt))
    .limit(1);

  if (open?.status === "uploaded") {
    return { kind: "existing", asset: open };
  }
  let abandoned: MediaAsset | null = null;
  if (open?.status === "pending_upload") {
    if (metadataOf(open).executionMode === "queued_worker") {
      // A worker may hold queued work, so age alone never abandons it, and the
      // same request is never recreated under another mode.
      const cancelled =
        isStaleQueuedRequest(open, config, now()) &&
        (await cancelStaleQueuedRequestInTx(tx, caller.tenantId, open, actorOf(caller)));
      if (!cancelled) {
        return { kind: "in_progress" };
      }
    } else if (now().getTime() < open.createdAt.getTime() + config.requestTimeoutMs + 60_000) {
      return { kind: "in_progress" };
    } else {
      abandoned = open;
    }
  }

  const used = await countAttemptsInWindow(tx, caller.tenantId, new Date(now().getTime() - QUOTA_WINDOW_MS));
  if (used >= config.dailyLimitPerTenant) {
    return { kind: "daily_limit_reached" };
  }

  const prompt = buildAiPhotoPrompt(product.context);
  const metadata: GenerationMetadata = {
    schema: AI_PHOTO_METADATA_SCHEMA,
    provider: config.provider,
    model: config.provider === "mock" ? "mock" : config.model,
    quality: config.quality,
    promptVersion: AI_PHOTO_PROMPT_VERSION,
    prompt,
    contextSha256: aiPhotoContextSha256(product.context),
    menuPublicId,
    requestedBySubject: caller.subject,
    requestedAt: now().toISOString(),
    executionMode: config.executionMode,
  };

  const grant = await createProductImageUploadGrantInTx(tx, caller.tenantId, product.publicId, {
    expectedByteSize: mediaConfig.maxUploadBytes,
    expectedContentType: "image/jpeg",
    sourceProvenance: "ai_generated",
    generationMetadata: metadata,
    altTextEn: `AI-generated image of ${product.context.displayName}`,
  });

  let spendReservationPublicId: string | null = null;
  if (config.executionMode === "queued_worker") {
    if (!context.spendPolicy) {
      throw new Error("Queued AI photos need a spend policy.");
    }
    const { reservation } = await reserveAiSpend(
      tx,
      {
        tenantId: caller.tenantId,
        path: AI_PHOTO_SPEND_PATH,
        provider: AI_PHOTO_SPEND_PROVIDER,
        subjectType: AI_PHOTO_SPEND_SUBJECT,
        subjectPublicId: grant.assetPublicId,
        units: 1,
        requestedBy: actorOf(caller),
      },
      { policy: context.spendPolicy, now: now() },
    );
    spendReservationPublicId = reservation.publicId;
    await tx
      .update(catalogueMediaAssets)
      .set({ generationMetadata: { ...metadata, spendReservationPublicId } })
      .where(eq(catalogueMediaAssets.id, grant.assetId));
    await enqueueAiJobInTx(tx, {
      tenantId: caller.tenantId,
      jobKind: AI_PHOTO_JOB_KIND,
      mediaAssetId: grant.assetId,
      now: now(),
    });
  }

  // An abandoned synchronous reservation (the request died mid-call) is closed out honestly.
  if (abandoned) {
    await tx
      .update(catalogueMediaAssets)
      .set({
        status: "failed",
        failureReason: "Generation did not finish.",
        generationMetadata: { ...metadataOf(abandoned), failureCode: "abandoned" },
        updatedAt: new Date(),
      })
      .where(eq(catalogueMediaAssets.id, abandoned.id));
  }

  await recordTenantAuditEventInTx(tx, {
    tenantId: caller.tenantId,
    actorSubject: caller.subject,
    actorClass: auditActorClassFromStaffRole(caller.membership.role),
    action: "catalogue.media.ai_photo_requested",
    entityType: "catalogue_media_asset",
    entityPublicId: grant.assetPublicId,
    changeSummary: {
      productPublicId: product.publicId,
      menuPublicId,
      model: config.model,
      quality: config.quality,
      executionMode: config.executionMode,
      ...(spendReservationPublicId ? { spendReservationPublicId } : {}),
      usedToday: used + 1,
      dailyLimit: config.dailyLimitPerTenant,
    },
  });

  const [asset] = await tx
    .select()
    .from(catalogueMediaAssets)
    .where(eq(catalogueMediaAssets.id, grant.assetId))
    .limit(1);
  return { kind: "reserved", asset: asset!, grantToken: grant.grantToken, prompt };
}

function requireGenerationAvailable(config: AiPhotoConfig, options: ServiceOptions) {
  const reason = resolveAvailability(config, options);
  if (reason === "spend_policy_unset") {
    throw new AiPhotoError(
      "spend_policy_unset",
      "AI photos are waiting for a spend policy. Ask your QOS operator to configure it.",
      409,
    );
  }
  if (reason) {
    throw new AiPhotoError("ai_photos_unavailable", "AI photos are not available for this business.", 409);
  }
}

function spendRefusal(error: unknown): never {
  if (error instanceof AiSpendAdmissionError) {
    throw new AiPhotoError(error.code, error.message, error.status);
  }
  throw error;
}

/**
 * Generates one reviewable candidate for a product on the menu. In `sync`
 * mode the provider is called inside this request; in `queued_worker` mode
 * the request is only admitted and the AI worker generates it. Either way the
 * candidate lands in private quarantine; nothing is attached or public until
 * an administrator accepts it.
 */
export async function generateMenuAiPhoto(
  db: DbClient,
  caller: AiPhotoCaller,
  input: { menuPublicId: string; productPublicId: string },
  options: ServiceOptions = {},
): Promise<GenerateAiPhotoResult> {
  const config = options.config ?? readAiPhotoConfig();
  const now = options.now ?? (() => new Date());
  requireAdministrator(caller);
  requireGenerationAvailable(config, options);
  const queued = config.executionMode === "queued_worker";
  const spendPolicy = queued ? (options.spendPolicy ?? readAiSpendPolicy()) : null;

  const reserved = await withTenantContext(db, caller.tenantId, async (tx) => {
    await assertMenuLocationAccess(tx, caller.tenantId, caller.membership, input.menuPublicId);
    await lockTenantAiPhotos(tx, caller.tenantId);
    const product = await requireMenuProduct(tx, caller.tenantId, input.menuPublicId, input.productPublicId);
    return reserveAiPhotoInTx(tx, caller, input.menuPublicId, product, { config, now, spendPolicy });
  }).catch(spendRefusal);

  const view = (asset: MediaAsset) =>
    toCandidateView(caller.tenantId, input.menuPublicId, input.productPublicId, asset);

  switch (reserved.kind) {
    case "existing":
      return { candidate: view(reserved.asset), created: false, queued: false };
    case "in_progress":
      throw new AiPhotoError("generation_in_progress", IN_PROGRESS_MESSAGE, 409);
    case "daily_limit_reached":
      throw new AiPhotoError("daily_limit_reached", dailyLimitMessage(config), 429);
  }
  if (queued) {
    return { candidate: view(reserved.asset), created: true, queued: true };
  }

  const asset = reserved.asset;
  let bytes: Buffer;
  let usage: AiPhotoUsage | null = null;
  try {
    const provider = options.provider ?? getAiPhotoProvider(config);
    const result = await provider.generate({ prompt: reserved.prompt, requestId: asset.publicId });
    usage = result.usage;
    bytes = await normalizeGeneratedImage(result.bytes);
  } catch (error) {
    const failure = providerFailure(error);
    console.warn("AI photo generation failed", {
      tenantId: caller.tenantId,
      assetPublicId: asset.publicId,
      failureCode: failure.failureCode,
      providerOutcome: failure.providerOutcome,
      ...failure.providerDiagnostics,
    });
    const failed = await markGenerationFailed(db, caller, asset.id, failure);
    if (!failed) {
      throw error;
    }
    return { candidate: view(failed), created: true, queued: false };
  }

  try {
    await ingestProductImageUpload(db, caller.tenantId, input.productPublicId, reserved.grantToken, bytes);
  } catch {
    const failed = await markGenerationFailed(db, caller, asset.id, {
      failureCode: "storage_failed",
      message: "The generated image could not be stored.",
    });
    return { candidate: view(failed!), created: true, queued: false };
  }

  const stored = await recordAiPhotoCompletion(db, caller.tenantId, asset.id, { usage, completedAt: now() });
  return { candidate: view(stored), created: true, queued: false };
}

/** What a provider (or output normalisation) failure proves, as recorded on the asset. */
export function providerFailure(error: unknown): AiPhotoFailure & { providerOutcome: ProviderOutcome } {
  if (error instanceof AiPhotoProviderError) {
    return {
      failureCode: error.code,
      message: error.message,
      providerOutcome: error.outcome,
      providerDiagnostics: error.diagnostics,
    };
  }
  return {
    failureCode: "provider_error",
    message: "The image service could not generate this photo.",
    providerOutcome: "submission_unknown",
  };
}

/** Records completion details on a stored candidate. Must run after the image was ingested. */
export async function recordAiPhotoCompletionInTx(
  tx: DbTransaction,
  tenantId: string,
  assetId: string,
  input: { usage: AiPhotoUsage | null; completedAt: Date },
) {
  const [asset] = await tx
    .select()
    .from(catalogueMediaAssets)
    .where(and(eq(catalogueMediaAssets.tenantId, tenantId), eq(catalogueMediaAssets.id, assetId)))
    .limit(1)
    .for("update");
  const [updated] = await tx
    .update(catalogueMediaAssets)
    .set({
      generationMetadata: {
        ...metadataOf(asset!),
        completedAt: input.completedAt.toISOString(),
        usage: input.usage,
      },
      updatedAt: new Date(),
    })
    .where(eq(catalogueMediaAssets.id, assetId))
    .returning();
  return updated!;
}

function recordAiPhotoCompletion(
  db: DbClient,
  tenantId: string,
  assetId: string,
  input: { usage: AiPhotoUsage | null; completedAt: Date },
) {
  return withTenantContext(db, tenantId, (tx) => recordAiPhotoCompletionInTx(tx, tenantId, assetId, input));
}

export type AiPhotoBatchOutcome =
  | "queued"
  | "existing_candidate"
  | "in_progress"
  | "daily_limit_reached"
  | "product_not_in_menu"
  | AiSpendAdmissionErrorCode;

export type AiPhotoBatchItem = {
  productPublicId: string;
  outcome: AiPhotoBatchOutcome;
  candidate: AiPhotoCandidateView | null;
  message: string | null;
};

/**
 * Admits a batch for the AI worker in one transaction under the tenant lock.
 * Each item is admitted on its own savepoint: what fits is queued, and every
 * item reports what happened to it. Only available in queued_worker mode.
 */
export async function queueMenuAiPhotoBatch(
  db: DbClient,
  caller: AiPhotoCaller,
  input: { menuPublicId: string; productPublicIds: readonly string[] },
  options: ServiceOptions = {},
): Promise<{ items: AiPhotoBatchItem[] }> {
  const config = options.config ?? readAiPhotoConfig();
  const now = options.now ?? (() => new Date());
  requireAdministrator(caller);
  if (config.executionMode !== "queued_worker") {
    throw new AiPhotoError("batch_unavailable", "Batch generation is not enabled for this environment.", 409);
  }
  requireGenerationAvailable(config, options);
  const productPublicIds = [...new Set(input.productPublicIds)];
  if (productPublicIds.length === 0 || productPublicIds.length > AI_PHOTO_MAX_BATCH) {
    throw new AiPhotoError(
      "invalid_batch",
      `Choose between 1 and ${AI_PHOTO_MAX_BATCH} items to generate.`,
      400,
    );
  }
  const spendPolicy = options.spendPolicy ?? readAiSpendPolicy();

  return withTenantContext(db, caller.tenantId, async (tx) => {
    await assertMenuLocationAccess(tx, caller.tenantId, caller.membership, input.menuPublicId);
    await lockTenantAiPhotos(tx, caller.tenantId);
    const products = await loadMenuProducts(tx, caller.tenantId, input.menuPublicId, productPublicIds);

    const items: AiPhotoBatchItem[] = [];
    for (const productPublicId of productPublicIds) {
      const item = (outcome: AiPhotoBatchOutcome, candidate: MediaAsset | null, message: string | null) =>
        items.push({
          productPublicId,
          outcome,
          candidate: candidate
            ? toCandidateView(caller.tenantId, input.menuPublicId, productPublicId, candidate)
            : null,
          message,
        });
      const product = products.get(productPublicId);
      if (!product) {
        item("product_not_in_menu", null, "This item is not on the menu.");
        continue;
      }
      try {
        const reserved = await tx.transaction((savepoint) =>
          reserveAiPhotoInTx(savepoint, caller, input.menuPublicId, product, { config, now, spendPolicy }),
        );
        switch (reserved.kind) {
          case "existing":
            item("existing_candidate", reserved.asset, null);
            break;
          case "in_progress":
            item("in_progress", null, IN_PROGRESS_MESSAGE);
            break;
          case "daily_limit_reached":
            item("daily_limit_reached", null, dailyLimitMessage(config));
            break;
          case "reserved":
            item("queued", reserved.asset, null);
            break;
        }
      } catch (error) {
        if (!(error instanceof AiSpendAdmissionError)) {
          throw error;
        }
        item(error.code, null, error.message);
      }
    }
    return { items };
  });
}

async function loadCandidate(
  tx: DbTransaction,
  tenantId: string,
  assetPublicId: string,
  options: { lock: boolean },
) {
  const query = tx
    .select()
    .from(catalogueMediaAssets)
    .where(
      and(
        eq(catalogueMediaAssets.tenantId, tenantId),
        eq(catalogueMediaAssets.publicId, assetPublicId),
        eq(catalogueMediaAssets.sourceProvenance, "ai_generated"),
      ),
    )
    .limit(1);
  const [asset] = options.lock ? await query.for("update") : await query;
  if (!asset) {
    throw new AiPhotoError("candidate_not_found", "AI photo not found.", 404);
  }

  const [product] = await tx
    .select({ publicId: catalogueProducts.publicId })
    .from(catalogueProducts)
    .where(and(eq(catalogueProducts.tenantId, tenantId), eq(catalogueProducts.id, asset.productId)))
    .limit(1);
  if (!product) {
    throw new AiPhotoError("candidate_not_found", "AI photo not found.", 404);
  }
  return { asset, productPublicId: product.publicId };
}

export type AcceptAiPhotoInput = {
  menuPublicId: string;
  assetPublicId: string;
  /** Staff confirmed the image fairly represents the item. Required. */
  accuracyConfirmed: boolean;
  /** Required when the item already has an approved photo. */
  replaceExisting?: boolean;
};

/**
 * Accepts a pending candidate through the normal derivative pipeline and
 * attaches it as the draft product's primary photo. Publishing the menu is a
 * separate action, so nothing goes live here.
 */
export async function acceptMenuAiPhoto(
  db: DbClient,
  caller: AiPhotoCaller,
  input: AcceptAiPhotoInput,
  options: ServiceOptions = {},
): Promise<AiPhotoCandidateView> {
  requireAdministrator(caller);
  const now = options.now ?? (() => new Date());

  return withTenantContext(db, caller.tenantId, async (tx) => {
    await assertMenuLocationAccess(tx, caller.tenantId, caller.membership, input.menuPublicId);
    const { asset, productPublicId } = await loadCandidate(tx, caller.tenantId, input.assetPublicId, { lock: true });
    const product = await requireMenuProduct(tx, caller.tenantId, input.menuPublicId, productPublicId);

    if (asset.status === "approved") {
      return toCandidateView(caller.tenantId, input.menuPublicId, productPublicId, asset);
    }
    if (asset.status !== "uploaded") {
      throw new AiPhotoError("candidate_not_reviewable", "This AI photo can no longer be accepted.", 409);
    }
    if (!input.accuracyConfirmed) {
      throw new AiPhotoError(
        "accuracy_review_required",
        "Confirm the image fairly represents the item before accepting it.",
        400,
      );
    }

    const metadata = metadataOf(asset);
    if (metadata.contextSha256 !== aiPhotoContextSha256(product.context)) {
      throw new AiPhotoError(
        "stale_candidate",
        "The item's name or description changed after this image was generated. Generate a new one.",
        409,
      );
    }

    const [lockedProduct] = await tx
      .select({ primaryMediaAssetId: catalogueProducts.primaryMediaAssetId })
      .from(catalogueProducts)
      .where(eq(catalogueProducts.id, product.id))
      .limit(1)
      .for("update");
    const existingThumbnails = await getApprovedThumbnailPublicIdsForProducts(tx, caller.tenantId, [
      { id: product.id, primaryMediaAssetId: lockedProduct?.primaryMediaAssetId ?? null },
    ]);
    const hasApprovedPhoto = existingThumbnails.has(product.id);
    if (hasApprovedPhoto && !input.replaceExisting) {
      throw new AiPhotoError(
        "existing_photo",
        "This item already has an approved photo. Confirm you want to replace it.",
        409,
      );
    }

    let replacedAssetPublicId: string | null = null;
    if (hasApprovedPhoto && lockedProduct?.primaryMediaAssetId) {
      const [replaced] = await tx
        .select({ publicId: catalogueMediaAssets.publicId })
        .from(catalogueMediaAssets)
        .where(eq(catalogueMediaAssets.id, lockedProduct.primaryMediaAssetId))
        .limit(1);
      replacedAssetPublicId = replaced?.publicId ?? null;
    }

    await processProductImageInTx(tx, caller.tenantId, productPublicId, asset.publicId, caller.subject);

    const [accepted] = await tx
      .update(catalogueMediaAssets)
      .set({
        generationMetadata: {
          ...metadata,
          review: {
            decision: "accepted",
            decidedBySubject: caller.subject,
            decidedAt: now().toISOString(),
            accuracyConfirmed: true,
            replacedAssetPublicId,
          },
        },
        updatedAt: new Date(),
      })
      .where(eq(catalogueMediaAssets.id, asset.id))
      .returning();

    await recordTenantAuditEventInTx(tx, {
      tenantId: caller.tenantId,
      actorSubject: caller.subject,
      actorClass: auditActorClassFromStaffRole(caller.membership.role),
      action: "catalogue.media.ai_photo_accepted",
      entityType: "catalogue_media_asset",
      entityPublicId: asset.publicId,
      changeSummary: { productPublicId, replacedAssetPublicId },
    });

    return toCandidateView(caller.tenantId, input.menuPublicId, productPublicId, accepted);
  });
}

/** Rejects a pending candidate. The product's current photo is untouched. */
export async function rejectMenuAiPhoto(
  db: DbClient,
  caller: AiPhotoCaller,
  input: { menuPublicId: string; assetPublicId: string },
  options: ServiceOptions = {},
): Promise<AiPhotoCandidateView> {
  const now = options.now ?? (() => new Date());

  return withTenantContext(db, caller.tenantId, async (tx) => {
    await assertMenuLocationAccess(tx, caller.tenantId, caller.membership, input.menuPublicId);
    const { asset, productPublicId } = await loadCandidate(tx, caller.tenantId, input.assetPublicId, { lock: true });
    await requireMenuProduct(tx, caller.tenantId, input.menuPublicId, productPublicId);

    if (asset.status === "rejected") {
      return toCandidateView(caller.tenantId, input.menuPublicId, productPublicId, asset);
    }
    if (asset.status !== "uploaded") {
      throw new AiPhotoError("candidate_not_reviewable", "This AI photo can no longer be rejected.", 409);
    }

    const [rejected] = await tx
      .update(catalogueMediaAssets)
      .set({
        status: "rejected",
        generationMetadata: {
          ...metadataOf(asset),
          review: {
            decision: "rejected",
            decidedBySubject: caller.subject,
            decidedAt: now().toISOString(),
          },
        },
        updatedAt: new Date(),
      })
      .where(eq(catalogueMediaAssets.id, asset.id))
      .returning();

    await recordTenantAuditEventInTx(tx, {
      tenantId: caller.tenantId,
      actorSubject: caller.subject,
      actorClass: auditActorClassFromStaffRole(caller.membership.role),
      action: "catalogue.media.ai_photo_rejected",
      entityType: "catalogue_media_asset",
      entityPublicId: asset.publicId,
      changeSummary: { productPublicId },
    });

    return toCandidateView(caller.tenantId, input.menuPublicId, productPublicId, rejected);
  });
}

/** Staff-only preview of a pending candidate from private quarantine storage. */
export async function readMenuAiPhotoPreview(
  db: DbClient,
  caller: AiPhotoCaller,
  input: { menuPublicId: string; assetPublicId: string },
) {
  const path = await withTenantContext(db, caller.tenantId, async (tx) => {
    await assertMenuLocationAccess(tx, caller.tenantId, caller.membership, input.menuPublicId);
    const { asset, productPublicId } = await loadCandidate(tx, caller.tenantId, input.assetPublicId, { lock: false });
    await requireMenuProduct(tx, caller.tenantId, input.menuPublicId, productPublicId);
    if (asset.status !== "uploaded") {
      throw new AiPhotoError("candidate_not_found", "AI photo not found.", 404);
    }
    const [grant] = await tx
      .select({ privateStoragePath: catalogueMediaUploadGrants.privateStoragePath })
      .from(catalogueMediaUploadGrants)
      .where(
        and(
          eq(catalogueMediaUploadGrants.tenantId, caller.tenantId),
          eq(catalogueMediaUploadGrants.assetId, asset.id),
          eq(catalogueMediaUploadGrants.status, "used"),
        ),
      )
      .limit(1);
    if (!grant) {
      throw new AiPhotoError("candidate_not_found", "AI photo not found.", 404);
    }
    return grant.privateStoragePath;
  });

  return { bytes: await getMediaStorage().readPrivate(path), contentType: "image/jpeg" };
}
